export const FORMULARIO_ANUNCIO = 'FORMULARIO_ANUNCIO';
export const FORMULARIO_EDICION ='FORMULARIO_EDICION';
export const FORMULARIO_CERRAR_EDICION ='FORMULARIO_CERRAR_EDICION';
export const OBTENER_ANUNCIOS = 'OBTENER_ANUNCIOS';
export const OBTENER_TAGS ='OBTENER_TAGS';
export const AGREGAR_ANUNCIO = 'AGREGAR_ANUNCIO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const ANUNCIO_ACTUAL = 'ANUNCIO_ACTUAL';
export const ELIMINAR_ANUNCIO = 'ELIMINAR_ANUNCIO';
export const ANUNCIO_ERROR = 'ANUNCIO_ERROR';
export const ANUNCIO_SELECTED = 'ANUNCIO_SELECTED';
export const ACTUALIZAR_ANUNCIO = 'ACTUALIZAR_ANUNCIO';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const RESETEAR_PASS = 'RESETEAR_PASS';
export const RESETEO_SOLICITADO = 'RESETEO_SOLICITADO';
export const NEW_PASSWORD = 'NEW_PASSWORD';

export const FORMULARIO_BUSQUEDA = 'FORMULARIO_BUSQUEDA';
export const URL_SEARCH = 'URL_SEARCH';
export const ANUNCIOS_BUSQUEDA = 'ANUNCIOS_BUSQUEDA';
export const BUSQUEDA_ERROR = 'BUSQUEDA_ERROR';